AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'db/**/*'
    - 'bin/*'

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'config/initializers/**/*.rb'

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
