AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'db/**/*'
    - 'bin/*'

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/**/*.rb'
Metrics/BlockLength:
  Max: 50

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
