default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rewards_development

test:
  <<: *default
  database: rewards_test

production:
  <<: *default
  database: rewards_production
  username: rewards
  password: <%= ENV['REWARDS_DATABASE_PASSWORD'] %>
